/** @type {import('sequelize-cli').Migration} */

module.exports = {
  async up(queryInterface) {
    await queryInterface.bulkInsert(
      "courses",
      [
        // Arquitetura e Urbanismo & Design
        {
          name: "Arquitetura e Urbanismo",
          category: "Arquitetura e Urbanismo & Design",
          duration_sem: 10,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Design",
          category: "Arquitetura e Urbanismo & Design",
          duration_sem: 6,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Design de Animação",
          category: "Arquitetura e Urbanismo & Design",
          duration_sem: 6,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Design de Games",
          category: "Arquitetura e Urbanismo & Design",
          duration_sem: 6,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Design de Interiores",
          category: "Arquitetura e Urbanismo & Design",
          duration_sem: 4,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Design de Moda",
          category: "Arquitetura e Urbanismo & Design",
          duration_sem: 6,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Design de Produto",
          category: "Arquitetura e Urbanismo & Design",
          duration_sem: 4,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Design Gráfico",
          category: "Arquitetura e Urbanismo & Design",
          duration_sem: 6,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Design Gráfico",
          category: "Arquitetura e Urbanismo & Design",
          duration_sem: 4,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },

        // Ciências Agrárias & Meio Ambiente
        {
          name: "Gestão Ambiental",
          category: "Ciências Agrárias & Meio Ambiente",
          duration_sem: 4,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Gestão Do Agronegócio",
          category: "Ciências Agrárias & Meio Ambiente",
          duration_sem: 6,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Medicina Veterinária",
          category: "Ciências Agrárias & Meio Ambiente",
          duration_sem: 10,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },

        // Ciências Biológicas e da Saúde
        {
          name: "Biomedicina",
          category: "Ciências Biológicas e da Saúde",
          duration_sem: 8,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Ciências Biológicas",
          category: "Ciências Biológicas e da Saúde",
          duration_sem: 8,
          degree: "Teaching",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Ciências Biológicas",
          category: "Ciências Biológicas e da Saúde",
          duration_sem: 8,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Educação Física",
          category: "Ciências Biológicas e da Saúde",
          duration_sem: 8,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Enfermagem",
          category: "Ciências Biológicas e da Saúde",
          duration_sem: 10,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Estética e Cosmética",
          category: "Ciências Biológicas e da Saúde",
          duration_sem: 5,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Farmácia",
          category: "Ciências Biológicas e da Saúde",
          duration_sem: 10,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Fisioterapia",
          category: "Ciências Biológicas e da Saúde",
          duration_sem: 10,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Gestão Hospitalar",
          category: "Ciências Biológicas e da Saúde",
          duration_sem: 6,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Nutrição",
          category: "Ciências Biológicas e da Saúde",
          duration_sem: 8,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Odontologia",
          category: "Ciências Biológicas e da Saúde",
          duration_sem: 10,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Radiologia",
          category: "Ciências Biológicas e da Saúde",
          duration_sem: 6,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },

        // Ciências Humanas
        {
          name: "Artes Visuais",
          category: "Ciências Humanas",
          duration_sem: 8,
          degree: "Teaching",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Ciências Sociais",
          category: "Ciências Humanas",
          duration_sem: 8,
          degree: "Teaching",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Filosofia",
          category: "Ciências Humanas",
          duration_sem: 8,
          degree: "Teaching",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Física",
          category: "Ciências Humanas",
          duration_sem: 8,
          degree: "Teaching",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Geografia",
          category: "Ciências Humanas",
          duration_sem: 8,
          degree: "Teaching",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "História",
          category: "Ciências Humanas",
          duration_sem: 8,
          degree: "Teaching",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Letras - Inglês",
          category: "Ciências Humanas",
          duration_sem: 8,
          degree: "Teaching",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Letras - Português",
          category: "Ciências Humanas",
          duration_sem: 8,
          degree: "Teaching",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Letras - Português e Inglês",
          category: "Ciências Humanas",
          duration_sem: 8,
          degree: "Teaching",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Letras: Língua Portuguesa",
          category: "Ciências Humanas",
          duration_sem: 8,
          degree: "Teaching",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Matemática",
          category: "Ciências Humanas",
          duration_sem: 8,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Matemática",
          category: "Ciências Humanas",
          duration_sem: 8,
          degree: "Teaching",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Pedagogia",
          category: "Ciências Humanas",
          duration_sem: 8,
          degree: "Teaching",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Psicologia",
          category: "Ciências Humanas",
          duration_sem: 10,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Química",
          category: "Ciências Humanas",
          duration_sem: 8,
          degree: "Teaching",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Serviço Social",
          category: "Ciências Humanas",
          duration_sem: 7,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },

        // Ciências Jurídicas
        {
          name: "Direito",
          category: "Ciências Jurídicas",
          duration_sem: 10,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Mediação",
          category: "Ciências Jurídicas",
          duration_sem: 4,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Segurança No Trânsito",
          category: "Ciências Jurídicas",
          duration_sem: 4,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Segurança Pública",
          category: "Ciências Jurídicas",
          duration_sem: 4,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Serviços Judiciais",
          category: "Ciências Jurídicas",
          duration_sem: 4,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Serviços Penais",
          category: "Ciências Jurídicas",
          duration_sem: 4,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },

        // Comunicação & Artes
        {
          name: "Cinema e Audiovisual",
          category: "Comunicação & Artes",
          duration_sem: 8,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Comunicação e Inteligência de Mercado",
          category: "Comunicação & Artes",
          duration_sem: 8,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Jornalismo",
          category: "Comunicação & Artes",
          duration_sem: 8,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Produção Audiovisual",
          category: "Comunicação & Artes",
          duration_sem: 4,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Publicidade e Propaganda",
          category: "Comunicação & Artes",
          duration_sem: 8,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Relações Públicas",
          category: "Comunicação & Artes",
          duration_sem: 8,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Social Media",
          category: "Comunicação & Artes",
          duration_sem: 4,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },

        // Engenharias
        {
          name: "Engenharia Ambiental",
          category: "Engenharias",
          duration_sem: 10,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Engenharia Civil",
          category: "Engenharias",
          duration_sem: 10,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Engenharia da Computação",
          category: "Engenharias",
          duration_sem: 10,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Engenharia de Controle e Automação",
          category: "Engenharias",
          duration_sem: 10,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Engenharia de Produção",
          category: "Engenharias",
          duration_sem: 10,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Engenharia de Software",
          category: "Engenharias",
          duration_sem: 8,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Engenharia Elétrica",
          category: "Engenharias",
          duration_sem: 10,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Engenharia Mecânica",
          category: "Engenharias",
          duration_sem: 10,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Engenharia Química",
          category: "Engenharias",
          duration_sem: 10,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Estatística",
          category: "Engenharias",
          duration_sem: 8,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Gestão da Produção Industrial",
          category: "Engenharias",
          duration_sem: 6,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },

        // Gestão & Negócios
        {
          name: "Administração",
          category: "Gestão & Negócios",
          duration_sem: 8,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Ciências Contábeis",
          category: "Gestão & Negócios",
          duration_sem: 8,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Ciências Econômicas",
          category: "Gestão & Negócios",
          duration_sem: 8,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Comércio Exterior",
          category: "Gestão & Negócios",
          duration_sem: 4,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Gestão Comercial",
          category: "Gestão & Negócios",
          duration_sem: 4,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Gestão da Inovação e Empreendedorismo Digital",
          category: "Gestão & Negócios",
          duration_sem: 4,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Gestão da Qualidade",
          category: "Gestão & Negócios",
          duration_sem: 4,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Gestão de Negócios Digitais",
          category: "Gestão & Negócios",
          duration_sem: 4,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Gestão de Recursos Humanos",
          category: "Gestão & Negócios",
          duration_sem: 4,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Gestão Financeira",
          category: "Gestão & Negócios",
          duration_sem: 4,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Gestão Pública",
          category: "Gestão & Negócios",
          duration_sem: 4,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Logística",
          category: "Gestão & Negócios",
          duration_sem: 4,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Marketing",
          category: "Gestão & Negócios",
          duration_sem: 4,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Marketing Digital",
          category: "Gestão & Negócios",
          duration_sem: 4,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Negócios Imobiliários",
          category: "Gestão & Negócios",
          duration_sem: 4,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Processos Gerenciais",
          category: "Gestão & Negócios",
          duration_sem: 4,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Relações Internacionais",
          category: "Gestão & Negócios",
          duration_sem: 8,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },

        // TI & Computação
        {
          name: "Análise e Desenvolvimento de Sistemas",
          category: "TI & Computação",
          duration_sem: 5,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Big Data e Inteligência Analítica",
          category: "TI & Computação",
          duration_sem: 5,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Ciência da Computação",
          category: "TI & Computação",
          duration_sem: 8,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Ciência de Dados",
          category: "TI & Computação",
          duration_sem: 8,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Gestão da Tecnologia da Informação",
          category: "TI & Computação",
          duration_sem: 5,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Jogos Digitais",
          category: "TI & Computação",
          duration_sem: 5,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Redes de Computadores",
          category: "TI & Computação",
          duration_sem: 5,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Segurança da Informação",
          category: "TI & Computação",
          duration_sem: 5,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Sistemas de Informação",
          category: "TI & Computação",
          duration_sem: 8,
          degree: "Bachelor",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Sistemas para Internet",
          category: "TI & Computação",
          duration_sem: 4,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },

        // Turismo & Hospitalidade
        {
          name: "Eventos",
          category: "Turismo & Hospitalidade",
          duration_sem: 4,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Gastronomia",
          category: "Turismo & Hospitalidade",
          duration_sem: 4,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          name: "Gestão de Turismo",
          category: "Turismo & Hospitalidade",
          duration_sem: 4,
          degree: "Associate",
          created_at: new Date(),
          updated_at: new Date(),
        },
      ],
      {},
    );
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete("courses", null, {});
  },
};
